# Generated by Django 3.0.6 on 2020-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='weekday_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekends_datetime',
            field=models.DateTimeField(),
        ),
    ]
